spring:
  application:
    name: service-gateway
  cloud:
    gateway:
      discovery:
        enable: true
        register-enabled: true
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        #Path ??????
        - id: baidu
          predicates:   #??
            - Path=/baidu
          uri: http://www.baidu.com  #??????



#????????  ??????health?info????
management:
  endpoints:
    web:
      exposure:
        include:  '*'
  endpoint:
    gateway:
      enabled: true


#spring:
#  cloud:
#    gateway:
#    routes:
#    - id: after_route
#    uri: https://example.org
#    predicates:
#    - Cookie=mycookie,mycookievalue
#
#management:
#  endpoints:
#    web:
#      expose:
#        include: '*'
